# Thanks for Elytrium/LimboAPI for some of the workflow file :D
name: MultiAuth Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'zulu'
        cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew shadowJar :api:jar --no-daemon
    - name: Upload MultiAuth
      uses: actions/upload-artifact@v4.6.2
      with:
        name: MultiAuth
        path: |
          core/build/libs/MultiAuth-*.jar
          api/build/libs/MultiAuth-*-Api.jar
    - uses: dev-drprasad/delete-tag-and-release@v0.2.1
      if: ${{ github.event_name == 'push' }}
      with:
        delete_release: true
        tag_name: dev-build
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Find git version
      id: git-version
      run: echo "id=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
    - name: Find the correct plugin JAR
      if: ${{ github.event_name == 'push' }}
      id: find-jar
      run: |
        output="$(find core/build/libs/ -name "MultiAuth-*.jar" ! -name "*-Api.jar" -type f -printf "%f\n")"
        echo "jarname=$output" >> $GITHUB_OUTPUT
    - name: Find the correct api JAR
      if: ${{ github.event_name == 'push' }}
      id: find-jar-api
      run: |
        output="$(find api/build/libs/ -name "MultiAuth-*-Api.jar" -type f -printf "%f\n")"
        echo "jarname=$output" >> $GITHUB_OUTPUT
    - name: Release the build
      if: ${{ github.event_name == 'push' }}
      uses: ncipollo/release-action@v1
      with:
        artifacts: core/build/libs/${{ steps.find-jar.outputs.jarname }},api/build/libs/${{ steps.find-jar-api.outputs.jarname }}
        body: ${{ join(github.event.commits.*.message, '\n') }}
        prerelease: true
        name: Dev-build ${{ steps.git-version.outputs.id }}
        tag: dev-build

